data:
    images:
        lena: ../data/lena.jpg
        
    video:
        movingcable: ../data/movingcable.mp4
        
activeContours:
    maxwidth: 1000
    encodeColors: 5
        
render:
    maxwidth: 200
    quick: True
        
verbose: True
debug: False