data:
    images:
        lena: ../data/lena.jpg
        
    video:
        movingcable: ../data/movingcable.mp4
        movingsquare: ../data/movingsquare.mp4
        
activeContours:
    maxwidth: 500
    encodeColors: 5
        
render:
    maxwidth: 200
    quick: True
        
verbose: True
debug: False